[tool.mypy]
strict = true
warn_return_any = false
disallow_subclassing_any = false
disallow_any_generics = false
disallow_untyped_decorators = false
implicit_reexport = true

[[tool.mypy.overrides]]
module = [
    "praw.*",
    "prawcore.*",
    "chalice.*",
    "dotenv.*",
    "sqlalchemy.*"
]
ignore_missing_imports = true

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.isort]
profile = "black"
